### ISSUE TITLE
How to use exceptions?

### ISSUE THREAD

**Issue by jrquirk** [alcap-org/AlcapDAQ#188]
I ran into a problem that could've been solved much quicker if rootana had crashed with a stacktrace ([here](https://github.com/alcap-org/AlcapDAQ/blob/develop/analyzer/rootana/src/framework/IdChannel.cpp#L45-L58)). I have some questions:
1. @benkrikler, can I change the IdChannel to just throw instead of returning unknowns? I can't think of a situation other than an exceptional one where we'd have an unrecognized channel. We can change this back later, you already have the enums and isValid method.
2. How do you get a backtrace to print out after an uncaught exception? I tried throwing some yesterday from the standard libraries and I just got "uncaught exception" messages.

**Comment by AndrewEdmonds11** [comment]
> I can't think of a situation other than an exceptional one where we'd have an unrecognized channel.

I've done it before when I've accidentally passed a bankname but then had the problem where I didn't know where it was being passed from. If there's a way to add a stacktrace or throw an exception that tells you where the problem came from, then I'm all for it :)

**Comment by litchfld** [comment]
> How do you get a backtrace to print out after an uncaught exception? I tried throwing some yesterday from the standard libraries and I just got "uncaught exception" messages.

The STL exceptions don't.  You need to explicitly record the backtrace at the point the exception occurred and then print it out after it is caught. 

I added a bunch of magic a week or so back to give you a nice talkative tree of exception classes. You need to include the file `AlcapExcept.h` and then subclass your exceptions from `Except::Base`. See the [doxygen documentation](http://alcap-org.github.io/doxygen/AlcapDAQ/develop/classExcept_1_1Base.html) for how to use them, but a summary:

``` C++
#include "AlcapExcept.h"
// 1. Use the macro to create an exception for the problem you've run into:
MAKE_EXCEPTION(Base, OhNoes);
MAKE_EXCEPTION(OhNoes, ReallyBadThing);
// [...]
//  2. The exceptions will then be in the Except:: namespace
throw Except::OhNoes();
//or
throw Except::ReallyBadThing();
```

Obviously you need to have used the `MAKE_EXCEPTION` macro in the same compilation unit, but it depends on the exception what makes most sense. If the exception is a general thing that might crop up anywhere, it makes sense to put it in an global exception header.  In our case, the code base is quite small so that should rarely be needed. Instead I suggest putting it in a class's .cpp file if it is only thrown by private methods, or in the header file if it can be thrown by public methods.

**Comment by jrquirk** [comment]
Thank you. I'll try it out. That answers everything.

**Comment by benkrikler** [comment]
> @benkrikler, can I change the IdChannel to just throw instead of returning unknowns? I can't think of a situation other than an exceptional one where we'd have an unrecognized channel. We can change this back later, you already have the enums and isValid method.

That's a good idea.  At the time I wrote this I don't think we were agreed on using exceptions, but it definitely makes sense now.

**Comment by benkrikler** [comment]
@litchfld, I've looked at the nd280 code this came from and I can see you split up the 'what' string from the 'backtrace'.  There's no public method that retrieves the backtrace nw though so I'm going to add a `bt` method (`backtrace` causes a name clash with the gnu method) to the `Except::Base` class which returns the c-string.

I'm also going to make sure the LoopSequence explicitly catches and prints the exception.

**Comment by AndrewEdmonds11** [comment]
I'm running into the following error:

```
Raw data tree contains 4007 entries.
Processing file, which may take a while...
Will analyse all 29 channels
Terminating due to unexpected exception:
map::at
```

How do I get the backtrace for this? Does it need to be explicitly called when this specific exception is thrown or can I set it to be done globally?

**Comment by benkrikler** [comment]
That's a std::exception which doesn't include a backtrace.  Best you can do is run it in gdb I think. 

It willl be caused by trying to get a value from a map with a key that the map doesn't contain (like `vector::at` throws when you request an out of range index).  

My guess is that you're trying to get a TAP or TDP from one of the global lists with a source ID that the lists don't contain?

**Comment by AndrewEdmonds11** [comment]
>  Best you can do is run it in gdb I think. 

I tried this but because the program exits normally it doesn't stop when the exception is thrown so it's hard to know where to start.

> My guess is that you're trying to get a TAP or TDP from one of the global lists with a source ID that the lists don't contain?

I'd guessed it was something like this but now you've written it down, I think I know where the problem's coming from. Cheers :smiley:

**Comment by AndrewEdmonds11** [comment]
> > My guess is that you're trying to get a TAP or TDP from one of the global lists with a source ID that the lists don't contain?
> 
> I'd guessed it was something like this but now you've written it down, I think I know where the problem's coming from. Cheers :smiley: 

Yep, it was the same problem we've seen before (with the PCF) where the channels for the generators don't exist in their constructor. I'll explain more on the pull request when I finish.

BTW I'm working on the TAPAlgorithm constructors if I hadn't mentioned that

**Comment by jrquirk** [comment]
I learned this the other day. You can have GDB pause after certain events, such as a `throw`. Type

```
(gdb) catch throw
```

And GDB will pause as soon as the first exception is thrown.

**Comment by benkrikler** [comment]
> I tried this but because the program exits normally it doesn't stop when the exception is thrown so it's hard to know where to start.

We've been catching all exceptions in `main.cpp` though we don't do very much with them.  The purpose for catching them, I guess is to allow us to try closing files and cleaning up before we abort, but since we don't know the cause of these exceptions at this point (they're "`unexpected`") I think it's better to throw them again exactly for debugging.  

I just pushed a commit that implements this, so perhaps you can test it Andy with the error you just had?

> I learned this the other day. You can have GDB pause after certain events, such as a throw. Type
> 
> ```
> (gdb) catch throw
> ```

That's very good to know!

**Comment by jrquirk** [comment]
If you throw them again their stack starts where they're rethrown. This was something I tried before the GDB thing. Even though rethrowing them doesn't solve this problem, it's still a good idea because the return value is non-zero.

**Comment by AndrewEdmonds11** [comment]
> I just pushed a commit that implements this, so perhaps you can test it Andy with the error you just had?

Cool. I'll be rebasing in a bit so I'll force my error again and let you know what happens.

**Comment by AndrewEdmonds11** [comment]
This is the error I get now:

```
Raw data tree contains 4007 entries.
Processing file, which may take a while...
Will analyse all 29 channels
terminate called after throwing an instance of 'std::out_of_range'
  what():  map::at
Terminating due to unexpected exception:
map::at
```

which is more informative but is it possible to get it to say where the exception was thrown? Maybe it's not possible and I guess it's not urgent since we can always use GDB with John's `catch throw` command.

**Comment by benkrikler** [comment]
By that point, no, if the exception is a simple std one or a primitive value.  If it's one of our own ones then yes, we can identify better, but we would probably want to catch it elsewhere.

Issue #175 was exactly about dealing with this.  I put in some of those changes, but they're not quite the whole thing cause I didn't want to cause too much carnage to Phill's event navigator.
